---
title: "TP3"
output: html_document
date: "2022-11-27"
---

## Libraries
```{r}
rm(list=ls())
library(dplyr) 
library(ggplot2) # Create Elegant Data Visualisations Using the Grammar of Graphics
library(mlogit) # Multinomial Logit Models
library(tidyverse)
```

# Load data
```{r}
df <- read_csv2("donnees_TP3.csv")

df$TEMPS.VP <- as.numeric(sub(",", ".", df$TEMPS.VP, fixed = TRUE))
df$TEMPS.TC <- as.numeric(sub(",", ".", df$TEMPS.TC, fixed = TRUE))

df$IPERE <- as.factor(df$IPERE)
#df$P_GRAGE <- as.factor(df$M_DOMSR)
df$M_DOMSR <- as.factor(df$M_DOMSR)
df$ID_PERS <- as.factor(df$ID_PERS)
df$M_NUMERO <- as.factor(df$M_NUMERO) 
df$ID_DEPLAC <- as.factor(df$ID_DEPLAC)
df$MOTIF <- as.factor(df$MOTIF)
df$D_DEPLAC <- as.factor(df$D_DEPLAC)
df$D_DESSR <- as.factor(df$D_DESSR)
df$D_GRHRE <- factor(df$D_GRHRE, levels=c('1', '2', '3', '4', '5', '6', '7'),
  labels=c('0h-4h59',
           '5h-8h59',
           '9h-11h59',
           '12h-14h59',
           '15h-18h59',
           '19h-23h59',
           '24h-28h'))

df$HRE2 <- factor(df$HRE2, levels=c('1', '2'),
  labels=c('Pointe',
           'Hors-pointe'))

  
#df$P_STATUT <- factor(df$P_STATUT, levels=c('1', '2', '3', '4', '5', '6', '7', '8'),
#  labels=c('Travailleur à temps plein',
#           'Travailleur à temps partiel',
#           'Étudiant / élève',
#           'Retraité',
#           'Autre',
#           'N/A',
#           'À la maison',
#           'Refus'))

# Puisqu'il y a vraiment peu d'observations pour les catégories "Autre", "N/A", "À la maison" et "Refus", on les regroupe sous la catégorie "Autre".
#> summary(df$P_STATUT)
#  Travailleur à temps plein Travailleur à temps partiel       Étudiant / élève       Retraité          Autre         N/A        À la maison       Refus
#                      38351                        3115                   1047            263            193           0                 41           4
df$P_STATUT <- factor(df$P_STATUT, levels=c('1', '2', '3', '4', '5', '6', '7', '8'),
  labels=c('Travailleur à temps plein',
           'Travailleur à temps partiel',
           'Étudiant / élève',
           'Retraité',
           'Autre',
           'Autre',
           'Autre',
           'Autre'))

df$P_PERMIS <- factor(df$P_PERMIS, levels=c('1', '2', '3', '4', '5'),
  labels=c('Oui',
           'Non',
           'Ne sait pas',
           'Refus',
           'Non applicable'))
df$P_MOBIL <- factor(df$P_MOBIL, levels=c('1', '2', '3', '4', '5', '6'),
  labels=c('Oui',
           'Non',
           'N/A',
           'Ne sait pas',
           'Refus',
           'Ne sait pas comment'))

df$REVENU <- factor(df$REVENU, levels=c('1', '2', '3', '4', '5', '6', '7', '8'),
  labels=c('<30000',
           '30000-59999',
           '60000-89999',
           '90000-119999',
           '12000-149999',
           '>150000',
           'Refus',
           'Ne sait pas'))

df$P_GRAGE <- factor(df$P_GRAGE, levels=c(1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16),
  labels=c('0 à 4',
           '5 à 9',
           '10 à 14',
           '15 à 19',
           '20 à 24',
           '25 à 29',
           '30 à 34',
           '35 à 39',
           '40 à 44',
           '45 à 49',
           '50 à 54',
           '55 à 59',
           '60 à 64',
           '65 à 69',
           '70 à 74',
           '75+'))

df$P_SEXE <- factor(df$P_SEXE, levels=c('1', '2'),
  labels=c('H', 'F'))

#df$MODE <- factor(df$MODE, levels=c('VP', 'TC', 'Bimodal', 'M', 'B', 'X'),
#  labels=c('Véhicule personnel',
#           'Transport collectif',
#           'Bimodal',
#           'Marche',
#           'Vélo',
#           'Autre'))

downtown = c(299436.06, 5040431.54) # In MTM NAD 83 (EPSG:32188)
df <- df %>%
 mutate(
  D_DISTANCE2DOWNTOWN_KM = (((D_DESXCOOR - downtown[1]) ** 2 + (D_DESYCOOR - downtown[2]) ** 2) ** (0.5)) / 1000,
 )

```

## Data cleaning and preparation
```{r}
# Keep only rows where TEMPS.VP and TEMPS.TC is valid
df <- df %>%
  filter(TEMPS.VP != 0 & TEMPS.TC != 0)

# Keep only rows where selected mode is car, public transport, walk or bike
df <- df %>%
  filter(MODE %in% c('VP', 'TC', 'M', 'B'))
  #filter(MODE %in% c('Véhicule personnel', 'Transport collectif', 'Marche', 'Vélo'))

# Remove rows where TEMPS.TC or TEMPS.VP is NaN
df <- df %>%
  filter(!is.na(TEMPS.TC))
df <- df %>%
  filter(!is.na(TEMPS.VP))

# Convert to wide format. This is required by the mlogit package.
df_long <- df %>%
  mlogit.data(shape = "wide",
              # Name of column with the choices
              choice = "MODE",
              # Numbers of columns with attributes that vary by alternative
              varying = 42:45)
df_long_viz = as.data.frame(df_long) # this is just so that we can visualize the df_long database in RStudio.
```

# Model
### Note à moi même:
J'ai testé le modèle nested logit mais ça dit "singular" donc ça marche pas
ou ça marche avec VP ou TC mais valeur inclusive est à deux donc les nids sont pas pertinents. Il faut dire ça dans le rapport

```{r}
ml0 <- mlogit(
  MODE ~ TEMPS | AR_JOBS30 + AL,
  df_long,
)
summary(ml0)
```

```{r}
ml1 <- mlogit(
  MODE ~ TEMPS | AR_JOBS30 + AL + HRE2,
  df_long,
)
summary(ml1)
```

```{r}
ml2 <- mlogit(
  MODE ~ TEMPS | AR_JOBS30 + AL + HRE2 + M_PERS + D_DISTANCE2DOWNTOWN_KM,
  df_long,
)
summary(ml2)
```



### Choses temporaires / brouillon
```{r}
p <- ggplot(df, aes(x=MODE, y=AR_JOBS30)) + 
  geom_boxplot()
p
```
```{r}
print(summary(df$AR_JOBS30))


```

```{r}
quantile(df$AR_JOBS30)
```

```{r}
df %>%
  filter(AR_JOBS30 <= 4575) %>%
  count()
```

